"use client";
import {useEffect,useState} from 'react';
const mail='mailto:joagonzalez166@gmail.com', cv='/assets/Joaquin-Gonzalez-CV.pdf', git='https://github.com/joagonzalez26', linkedin='https://www.linkedin.com/in/joagonzalez26/';
function Arrow(){return <svg className="arrow-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>}
function CodeOrbit(){return <svg className="code-orbit" width="92" height="92" viewBox="0 0 92 92" fill="none" aria-hidden="true"><g className="orbit-ring"><circle cx="46" cy="46" r="39" stroke="currentColor" strokeOpacity=".2" strokeDasharray="2 6"/><circle cx="46" cy="7" r="3" fill="currentColor"/></g><circle cx="46" cy="46" r="31" stroke="currentColor" strokeOpacity=".12"/><path d="m36 38-8 8 8 8m20-16 8 8-8 8M50 34l-8 24" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Tags({items}:{items:string[]}){return <div className="tags">{items.map(x=><span key={x}>{x}</span>)}</div>}
function Label({n,children}:{n:string,children:React.ReactNode}){return <p className="label"><span>{n}</span>{children}</p>}
const screens=[['dashboard','Panel de inicio','Una vista central de estados, actividad y cédulas para acompañar la operación diaria.'],['login','Acceso al sistema','Una propuesta de acceso institucional con jerarquía clara y una experiencia de ingreso simple.'],['asistente','Asistente IA','Consultas en lenguaje natural sobre datos ficticios locales. El prototipo no modifica registros.']];
export default function Home(){const[menu,setMenu]=useState(false);
useEffect(()=>{
  const motion=window.matchMedia('(prefers-reduced-motion: reduce)');
  if(motion.matches || !('IntersectionObserver' in window)) return;
  const elements=Array.from(document.querySelectorAll<HTMLElement>('.section > h2, .section > .wrap > h2, .about h2, .case-title h2, .cards article, .main-shot, .gallery figure, .ai-feature, .contact h2'));
  const show=(el:HTMLElement)=>{el.classList.remove('reveal-pending');el.classList.add('reveal-shown');};
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{
    if(entry.isIntersecting){show(entry.target as HTMLElement);observer.unobserve(entry.target);}
  }),{threshold:0.08,rootMargin:'0px 0px -24px 0px'});
  elements.forEach((el,index)=>{
    el.classList.add('scroll-reveal');
    if(el.matches('.main-shot, .gallery figure'))el.classList.add('reveal-scale');
    if(el.matches('h2'))el.classList.add('reveal-title');
    if(el.matches('.cards article'))el.style.setProperty('--reveal-delay',`${index%3*70}ms`);
    if(el.getBoundingClientRect().top>window.innerHeight*.88){el.classList.add('reveal-pending');observer.observe(el);}
  });
  const focusReveal=(event:FocusEvent)=>{if(event.target instanceof Element){const el=event.target.closest<HTMLElement>('.reveal-pending');if(el){show(el);observer.unobserve(el);}}};
  const reduce=()=>{if(motion.matches){observer.disconnect();elements.forEach(show);}};
  document.addEventListener('focusin',focusReveal);motion.addEventListener('change',reduce);
  return()=>{observer.disconnect();document.removeEventListener('focusin',focusReveal);motion.removeEventListener('change',reduce);elements.forEach(show);};
},[]);
useEffect(()=>{
  if(!menu)return;
  const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(false);document.getElementById('menu-toggle')?.focus();}};
  document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);
},[menu]);
return <>
<a className="skip" href="#contenido">Saltar al contenido</a><header><nav className={menu?'open':''} id="nav" aria-label="Navegación principal">{[['Sobre mí','sobre-mi'],['Proyectos','proyectos'],['Enfoque','enfoque'],['Formación','formacion']].map(([t,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{t}</a>)}<a className="nav-cta" href="#contacto" onClick={()=>setMenu(false)}>Hablemos <Arrow/></a></nav><button id="menu-toggle" className="menu" aria-expanded={menu} aria-controls="nav" onClick={()=>setMenu(!menu)}>{menu?'Cerrar':'Menú'}</button></header>
<main id="contenido"><section className="hero wrap" id="inicio"><div className="hero-top"><span>Córdoba, Argentina</span></div><h1>JOAQUIN<br/><span>GONZALEZ</span>.</h1><div className="hero-grid"><div><p className="role">Analista en Sistemas – Calidad de Software<br/>– Integraciones IA – Desarrollo IT</p><p className="lead">Diseño, desarrollo y valido soluciones digitales uniendo software, QA, automatización e IA.</p><div className="actions"><a className="button dark" href={cv} download>Descargar CV <span>↓</span></a><a className="button outline" href={mail}>Enviar email <span>↗</span></a><a className="text-link" href="#proyectos">Ver proyectos ↘</a></div></div><aside className="hero-portrait"><img src="/images/technologist.png" alt="Personaje 3D de un joven con computadora portátil, estilo emoji" width="1024" height="1024" fetchPriority="high"/><div className="orbit-badge"><CodeOrbit/></div></aside></div><div className="hero-foot"><p>Software, calidad y automatización pensados como una sola disciplina.</p><a href="#sobre-mi" aria-label="Continuar a Sobre mí">↓</a></div></section>
<section className="wrap section about" id="sobre-mi"><Label n="01">SOBRE MÍ</Label><div><h2>Una mirada integral.<br/><em>De punta a punta.</em></h2><p className="large">Me interesa entender cómo funciona un proceso y convertirlo en una solución digital útil, clara y bien diseñada.</p><p>Trabajo en la intersección entre análisis, desarrollo, calidad y automatización. Me involucro desde el relevamiento y la planificación hasta el testing, la documentación y la validación final, cuidando tanto la lógica del sistema como la experiencia de uso.</p><div className="process"><span>Entender</span><span>Construir</span><span>Validar</span><span>Mejorar</span></div></div></section>
<section className="wrap section experience" id="experiencia"><Label n="02">EXPERIENCIA RELEVANTE</Label><h2>Trabajo con <em>contexto real.</em></h2><div className="cards"><article><span className="eyebrow">01 / PROYECTO INSTITUCIONAL</span><h3>Sistema de<br/>Gestión Judicial</h3><p className="card-role">Análisis, desarrollo, QA e integración funcional</p><p>Proyecto para un Juzgado de Paz del Poder Judicial de Córdoba. Relevamiento, organización funcional, desarrollo y validación de una aplicación para gestionar cédulas judiciales.</p><a className="text-link" href="#proyectos">Explorar el caso ↗</a></article><article><span className="eyebrow">02 / LABORATORIO PROPIO</span><h3>CaseFlow<br/>QA Engineering Lab</h3><p className="card-role">Laboratorio de ingeniería y calidad</p><p>Un espacio de práctica para arquitectura backend, persistencia, testing automatizado, calidad de código y documentación técnica, con un flujo de trabajo profesional.</p><Tags items={['FastAPI','PostgreSQL','Testing']}/></article><article><span className="eyebrow">03 / AUTOMATIZACIONES</span><h3>Automation<br/>& Integrations</h3><p className="card-role">Conexión entre herramientas y procesos</p><p>Flujos con APIs y n8n para reducir tareas repetitivas. Entre ellos, una integración de Obsidian con Google Calendar que valida fechas y evita eventos duplicados.</p><Tags items={['n8n','APIs','JavaScript']}/></article></div></section>
<section className="case" id="proyectos"><div className="wrap"><Label n="03">PROYECTO DESTACADO</Label><div className="case-title"><h2>Sistema de<br/><em>Gestión Judicial.</em></h2><p>Digitalización de procesos internos<br/>para la gestión de cédulas judiciales.</p></div><div className="case-meta"><span>Poder Judicial de Córdoba · Juzgado de Paz</span><span>Análisis / Desarrollo / QA / Diseño</span></div><aside className="case-scope"><strong>Alcance del caso</strong><p>El caso describe el trabajo de análisis, desarrollo y QA del proyecto. Las capturas muestran un prototipo de presentación con datos ficticios; la asistencia IA conectada al backend y las automatizaciones ampliadas se presentan como líneas de evolución.</p></aside><figure className="main-shot"><div className="image-bar"><span>SECURITY MAX — VISTA GENERAL</span><span>PROTOTIPO DE INTERFAZ</span></div><a href="/images/judicial-dashboard-v2.png" target="_blank" rel="noreferrer" aria-label="Abrir panel de inicio en tamaño completo"><img src="/images/judicial-dashboard-v2.png" alt="Panel de inicio de Security Max con resumen de cédulas y actividad reciente" width="2048" height="1066"/></a><figcaption>Un punto de acceso a la información operativa. Captura del prototipo presentado, no del entorno de producción.</figcaption></figure>
<div className="two-col story"><div><span className="eyebrow">EL CONTEXTO</span><h3>Dar orden.<br/>Hacer visible el proceso.</h3></div><div><p>La gestión de cédulas requiere organizar documentación, consultar estados y seguir cada movimiento. El proyecto aborda esa necesidad mediante una aplicación web orientada al trabajo interno.</p><p>El objetivo: centralizar la información, facilitar su consulta y acompañar la trazabilidad de los procesos con una experiencia simple.</p></div></div><div className="two-col details"><article><span className="eyebrow">MI PARTICIPACIÓN</span><h3>Del relevamiento<br/>a la validación.</h3><ul className="check-list">{['Análisis del problema y relevamiento de necesidades','Diseño funcional y estructura del sistema','Desarrollo de interfaz y organización de datos','Testing de UI y API, validación y documentación','Exploración de automatización y asistencia con IA'].map(x=><li key={x}>{x}</li>)}</ul></article><article className="architecture"><span className="eyebrow">ARQUITECTURA DEL PROYECTO</span>{[['React','Interfaz y experiencia de uso'],['FastAPI · APIs REST','Lógica del sistema y comunicación'],['PostgreSQL','Persistencia y organización de datos']].map(([t,d],i)=><div className="arch-row" key={t}><span>0{i+1}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}<p className="small">QA y validación a lo largo del proceso.<br/>n8n e IA como líneas de integración y evolución.</p></article></div>
<div className="gallery-heading"><h3>El sistema, <em>en pantalla.</em></h3><p>Tres vistas del prototipo. Seleccioná una captura para verla en tamaño completo.</p></div><div className="gallery">{screens.map(([img,t,d],i)=><figure key={img}><a href={'/images/judicial-'+img+'-v2.png'} target="_blank" rel="noreferrer" aria-label={'Ver '+t+' en tamaño completo (nueva pestaña)'}><img src={'/images/judicial-'+img+'-v2.png'} alt={t+': '+d} width="2048" height="1066" loading="eager" decoding="async"/><span className="expand"><Arrow/></span></a><figcaption><h4><span>0{i+1}</span>{t}</h4><p>{d}</p></figcaption></figure>)}</div>
<div className="ai-feature"><div><span className="eyebrow">IA APLICADA · EXPLORACIÓN FUNCIONAL</span><h3>Preguntar también<br/>puede ser <em>navegar.</em></h3><p>La propuesta incorpora una capa de asistencia para consultar información en lenguaje natural: buscar cédulas, contar registros, resumir estados y facilitar el acceso a la información.</p><p>La captura muestra un prototipo con respuestas basadas en datos ficticios locales. La conexión al backend y las validaciones de acciones sensibles forman parte de su evolución.</p><Tags items={['Lenguaje natural','Búsqueda contextual','Resúmenes','Conteos','Asistencia operativa']}/></div><div className="ai-quote"><span aria-hidden="true">“</span><blockquote>La IA amplía la experiencia.<br/><em>La lógica del sistema<br/>sigue siendo la base.</em></blockquote><p>Asistencia contextual, con límites claros.</p></div></div>
<div className="two-col closing"><article><span className="eyebrow">LÍNEA DE EVOLUCIÓN</span><h3>Conectar el siguiente paso.</h3><p>La arquitectura contempla ampliar las integraciones mediante APIs, n8n y posibles conexiones con canales como WhatsApp para acompañar la comunicación y el seguimiento operativo. Son líneas de evolución; no se presentan como funcionalidades completas del prototipo.</p></article><article><span className="eyebrow">APRENDIZAJES</span><h3>El valor está en el proceso.</h3><p>Análisis funcional aplicado a un caso real. Construcción de un sistema web completo. Desarrollo y QA trabajando juntos. Y una idea que atraviesa todo: los procesos complejos necesitan interfaces claras y trazabilidad.</p></article></div><aside className="confidential"><span>↳</span><p><strong>Sobre la confidencialidad.</strong> Por la naturaleza institucional y sensible del proyecto, el código fuente completo no se publica en repositorios públicos. Este caso presenta una síntesis visual, funcional y técnica; las imágenes corresponden a un prototipo de presentación con datos ficticios y no exponen registros de producción.</p></aside></div></section>
<section className="wrap section approach" id="enfoque"><Label n="04">CÓMO TRABAJO</Label><h2>Calidad, conexiones<br/><em>y criterio de diseño.</em></h2><article className="discipline"><div><span className="eyebrow">01 / CALIDAD</span><h3>Comprender.<br/>Anticipar. Validar.</h3></div><div><p className="large">La calidad empieza mucho antes del primer error.</p><p>Busco comprender el producto, anticipar riesgos y validar procesos desde las etapas tempranas. Diseño casos de prueba, documento evidencias y conecto requerimientos con criterios de aceptación claros.</p><p>La experiencia en crowdtesting con uTest / Applause complementa esa mirada con pruebas funcionales, exploratorias y mobile en ciclos reales.</p><Tags items={['QA manual','QA automation','Testing de APIs','Trazabilidad','Documentación','Mejora continua']}/></div></article><article className="discipline"><div><span className="eyebrow">02 / AUTOMATIZACIÓN E IA</span><h3>Menos repetición.<br/>Más intención.</h3></div><div><p className="large">Conectar herramientas para que el trabajo fluya.</p><p>Integro APIs, servicios y herramientas de IA en procesos concretos. Me interesa que cada automatización tenga un propósito claro, valide sus entradas y pueda mantenerse y entenderse.</p><div className="workflow"><span className="eyebrow">UN FLUJO REAL</span><p>Obsidian → n8n → Google Calendar</p><small>Tareas Markdown convertidas en eventos, con validación de fechas y control de duplicados.</small></div><Tags items={['n8n','APIs','Integraciones entre sistemas','IA aplicada','Flujos asistidos']}/></div></article><article className="discipline"><div><span className="eyebrow">03 / DESIGN ENGINEERING</span><h3>Simple a la vista.<br/>Cuidado en detalle.</h3></div><div><p className="large">La interfaz también es parte de la solución.</p><p>Mi enfoque une diseño e ingeniería para crear interfaces claras, simples y consistentes. El movimiento tiene una función: orientar la atención, explicar un cambio o dar feedback inmediato.</p><p>Tomo como referencias conceptuales las guías Emil Kowalski Skills y principios de interacción inspirados en Apple. Los traduzco en decisiones propias de jerarquía, consistencia espacial, coherencia visual y accesibilidad, adaptadas a cada producto.</p><Tags items={['Claridad','Simplicidad','Motion funcional','Feedback inmediato','Coherencia visual','Accesibilidad']}/></div></article></section>
<section className="education section" id="formacion"><div className="wrap"><Label n="05">FORMACIÓN Y APRENDIZAJE</Label><h2>Una base sólida.<br/><em>Aprendizaje continuo.</em></h2><div className="two-col education-grid"><div><span className="eyebrow">UNIVERSIDAD SIGLO 21</span><h3>Licenciatura<br/>en Informática</h3><p>Estudiante avanzado · Tramo final<br/>Beca de alto rendimiento</p><div className="degree"><strong>Analista Universitario en Sistemas de Computación</strong><p>Trayecto de título intermedio de la carrera.</p></div></div><div className="courses">{[['Full Stack Development','ITBA / Santander · Programa 2026'],['Google UX Design','Google / Coursera · Certificado profesional en curso'],['QA Automation y Python','Formación y práctica en automatización de pruebas. Python: Santander Open Academy.'],['Herramientas complementarias','Aprendizaje continuo en AWS, SQL, Git, APIs e IA aplicada.']].map(([t,d])=><div key={t}><h4>{t}</h4><p>{d}</p></div>)}</div></div></div></section>
<section className="wrap section" id="stack"><Label n="06">STACK Y HERRAMIENTAS</Label><h2>La herramienta correcta.<br/><em>Para cada problema.</em></h2><div className="stack">{[['Desarrollo',['React','FastAPI','Python','PostgreSQL','APIs REST','Git / GitHub']],['Calidad',['Playwright','Selenium','Pytest','Postman','QA manual','Documentación']],['Automatización e IA',['n8n','Integraciones','IA aplicada','Flujos asistidos','APIs','Productividad técnica']],['Diseño y procesos',['Análisis funcional','Diseño de interfaz','Arquitectura','Trazabilidad','Criterios de testing','Mejora continua']]].map(([t,items])=><div key={t as string}><h3>{t}</h3><ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul></div>)}</div></section>
<section className="contact" id="contacto"><div className="wrap"><div className="contact-top"><Label n="07">SIGUIENTE CONVERSACIÓN</Label><span>CÓRDOBA, ARGENTINA · REMOTO</span></div><h2>Trabajemos<br/><em>juntos.</em><span aria-hidden="true">↗</span></h2><div className="contact-bottom"><p>Si querés conocer más sobre mi experiencia, mis proyectos o explorar oportunidades de trabajo y colaboración, conversemos.</p><div><a className="email" href={mail}>joagonzalez166@gmail.com</a><div className="actions"><a className="button light" href={cv} download>Descargar CV ↓</a><a className="button outline" href={mail}>Enviar email ↗</a><a className="text-link" href={git} target="_blank" rel="noreferrer">GitHub <Arrow/></a><a className="text-link" href={linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow/></a></div></div></div><footer><span>© 2026 Joaquin Gonzalez</span><span>Software, calidad y criterio.</span><a href="#inicio">Volver arriba ↑</a></footer></div></section></main></>}
